language: c

before_install:
    - sudo apt-get update
    - sudo apt-get -y install cmake
    - git clone https://github.com/DaveGamble/cJSON.git
    - cd cJSON
    - mkdir build
    - cd build
    - cmake ..
    - make
    - sudo make install
    - cd ../../
    -
compiler:
    - clang
    - gcc

script:
    - mkdir build 
    - cd build 
    - cmake .. 
    - make
