language: c

before_install:
    - sudo apt-get update
    - sudo apt-get -y install cmake libtar libtar-dev
    - git clone https://github.com/DaveGamble/cJSON.git
    - cd cJSON
    - mkdir build
    - cd build
    - cmake ..
    - make
    - sudo make install
    - cd ../../
    
compiler:
    # cannot use clang due to sudo and travis not including clang in sudo path
    - gcc
    - clang

script:
    - mkdir build 
    - cd build 
    - cmake .. 
    - make

before_deploy:
    - mkdir export
    - mv uspm* export/
    - cd export
    - tar cf uspm-linux.tar ./*
    - mv uspm-linux.tar ../../
    - mv uspm-linux.tar "uspm-linux-${CC}.tar"
    - cd ../../

deploy:
    provider: releases
    api_key: $ghtoken
    file: "uspm-linux-${CC}.tar"
    skip_cleanup: true
    on:
        tags: true